#!/usr/bin/perl -w

use strict;
use BSON 0.12;
use warnings FATAL => qw(all);
use 5.10.0;

my $proxy_lport = 27017; # What port do we listen on?
my $proxycfg = "file:mongoe.cfg"; # Right now this is the only cfg method

##
# Plumbing for the 1.x (not 0.x!) version of the Mongo Perl bindings
use lib '.'; # Only needed if you've unpacked the Perl mongo driver as a subdir of here
use MongoDB::_Protocol;
use MongoDB::_Link;
use MongoDB::Error;
##

my $proxy; # Holds global proxy state

##
# Plumbing for Net::Server, which manages connections
# so I just write a handler for incoming clients
package MongoProxy;
use base qw(Net::Server);
use Data::Dumper;
$Data::Dumper::Indent=3;
#

main();

###################
# mongoe
#
# Calls private methods of the Perl Mongo driver (1.x)
# Sorry about that
#
# Author: Pat Gunn <pgunn@dachte.org>
# Copyright MongoDB 2015
# Apache License

sub process_request
{	# When you use Net::Server, you provide an entry point for
	# handling incoming connections, and it spawns a thread per
	# client, beginning execution at that entry point with STDIN/STDOUT
	# mapped to the network socket. This is that entry point for
	# mongoe
	#
	# http://docs.mongodb.org/meta-driver/latest/legacy/mongodb-wire-protocol/
	# Documents the formatting of the messages being passed back and forth.
	# If you modify this, be meticulous with reading that so you don't create
	# deadlocks

my ($self) = @_;
my $client = *STDIN;
binmode $client;
binmode STDOUT;
my $pool;
while(! eof($client))
	{
	# Read the 4 int32 fields that are the MsgHeader
	my $request;
	$request = ""; # Empty. Not sure if this can happen.
	my %req = read_message($client);
	print STDERR info_message(%req);
	my $conn = ensure_mongo_connection($pool, route_for_destination($req{schema}));
	$conn->write($req{raw});
	if(! $conn->remote_connected() )
		{print STDERR "Warning: mongod for $req{schema} has disconnected\n";}
	my $resp = $conn->read(); # TODO I need to add a handler for NetworkError events.
	my %respinfo = parse_reply($resp); # Already been read in, parse it
	print STDERR info_message(%respinfo);
	# TODO do something with %respinfo
	print $resp;
	}
}

sub cleaner($)
{	# Wire protocol details include binary data but are still potentially
	# interesting to log. This cleans them up for display
my ($toclean) = @_;
$toclean =~ s/[^[:ascii:]]/\?/g;
$toclean =~ s/[^[:print:]]/\?/g;
$toclean =~ tr/\n\f\r/\?/d;
return $toclean;
}

##################
# Router

sub setup_proxy($)
{	# Read the proxy config string, setup the global proxy state
	# (hashref) for what schema maps to where
my ($cfg) = @_;
my %ret;

my ($mode, $args) = split(':', $cfg, 2);
if($mode eq 'file')
	{%ret = load_proxyinfo_from_file($args);}
else	{die "Unsupported proxy method [$mode]\n";}

return \%ret;
}

sub load_proxyinfo_from_file($)
{	# Load a colon-separated file that maps:
	# SCHEMA:HOST:PORT
my ($fn) = @_;
my %ret;
open(my $fh, $fn) || die "Could not open proxy descriptor file [$fn]:$!\n";
while(<$fh>)
	{
	tr/\n\r\f//d; # Remove newlines and stuff
	s/#.*//; # Strip comments
	s/^\s+//;
	s/\s+$//;
	next if(/^$/); # Skip blank lines
	my($schema, $host, $port) = split(':', $_);
	$ret{$schema}{host} = $host;
	$ret{$schema}{port} = $port;
	#print "Learned schema [$schema]\n";
	}
close($fh);
if(! defined($ret{_DEFAULT}))
	{die "You must define a _DEFAULT schema\n";}

return %ret;
}

sub route_for_destination($)
{	# Given a schema, return the (host,port) pair it maps to
my ($schema) = @_;

my ($host, $port); # Return this
if(! defined($$proxy{$schema}))
	{$schema = "_DEFAULT";} # We should always have entries for this

$host = $$proxy{$schema}{host};
$port = $$proxy{$schema}{port};
return ($host, $port);
}

##################
# Wire Protocol and BSON stuff

sub bson_docset_to_docarray($;$)
{	# Given BSON data that can contain multiple documents, and a specifier
	# how many how many documents should be in there, return an array of
	# those documents.
my ($data, $numdocs) = @_;
my @ret;
while(length($data))
	{
	open(my $dfh, "<", \$data) || die "Failed to disassemble data: $!\n";
	read($dfh, my $msglen, 4) || die "Misparse in data disassembly: Partial document read\n";
	close($dfh);
	my $msglen_decoded = unpack('l', $msglen);
	my $thisdoc = substr($data, 0, $msglen_decoded, ''); # Destructive substr
	push(@ret, $thisdoc);
	if(defined $numdocs)
		{$numdocs--;}
	}
if( (defined $numdocs) && ($numdocs != 0))
	{die "Protocol error in unpacking BSON docset\n";}
print STDERR "PARSED: I saw " . scalar(@ret) . " DOCUMENTS\n";
return @ret;
}

sub info_message(%)
{	# TODO When we can decode BSON better, we can make this much, much nicer.
	#	We may eventually pull all this stuff into an object interface, which
	#	would make the code cleaner too.
my %msg = @_;
my $ret = '';
$ret .= "Message(" . $msg{msglen_decoded} . "): " . $msg{opname} . "(" . $msg{opcode_decoded} . ")\n";
$ret .= "\tSchema: " . (defined($msg{schema}) ? $msg{schema} : 'UNKNOWN') . "\n";
$ret .= "\tTable: " . (defined($msg{table}) ? $msg{table} : 'UNKNOWN') . "\n";
if(defined $msg{bson})
	{
	$ret .= "--------BEGIN DUMPER--------\n";
	$ret .= Dumper($msg{bson}) . "\n";
	$ret .= "--------END DUMPER--------\n";
	}
#$ret .= "\t[" . cleaner($msg{raw}) . "]\n";
return $ret;
}

sub parse_reply($)
{	# parse the reply sent by a backend server
my ($resp) = @_;

open(my $rfh, "<", \$resp) || die "Failed to open response: $!\n";
my %ret = read_message($rfh);
close($rfh);
return %ret;
}

sub read_message($)
{
my ($fh) = @_;

my %ret;
read($fh, $ret{msglen}, 4); # Size of messages in bytes, including header!
read($fh, $ret{reqid} , 4);
read($fh, $ret{respto}, 4);
read($fh, $ret{opcode}, 4);
$ret{raw} = join('', @ret{"msglen", "reqid", "respto", "opcode"});
$ret{msglen_decoded} = unpack('l', $ret{msglen});
$ret{opcode_decoded} = unpack('l', $ret{opcode});
my $content;

if($ret{msglen_decoded} > 16)
	{read($fh, $content, ($ret{msglen_decoded} - 16));}

parse_op($ret{opcode}, $content, \%ret);

$ret{raw} .= $content;
return %ret;
}

sub parse_op($$$)
{	# Pass in: (non-decoded) opcode, request
	# Passes back: opname, schema, table
	# TODO: opcode is part of opinfo. Refactor arg passing
my ($opcode, $request, $opinfo) = @_;

my $opcode_d = unpack('l', $opcode);
if($opcode_d == 2001) # OP_UPDATE
	{
	my (undef, $coll) = unpack("lZ*", $request); # ZERO, collection, flags, selectorDocument, updateDocument
	my $selectordoc = substr($request, 9+length($coll)); # 2L + strlen + null-termination
		# TODO The selectordoc starts with an int32 that's its (packed) length.
		# We should substr once (no-replace) to pull the updatedocument out,
		# then substr again (with replace) to trim the selectordoc down to its desired parts.
	my ($schema, $table) = split(/\./, $coll);
	@$opinfo{'opname','schema','table'} = ('OP_UPDATE', $schema, $table);
	}
elsif($opcode_d == 2002) # OP_INSERT
	{
	my (undef, $coll) = unpack("lZ*", $request); # Flags, collection, documents
	my $qdoc = substr($request, 5+length($coll)); # 1L + strlen + null-termination
	my @dec_docset = map
				{
				BSON::decode($_, ixhash=>1)
				} bson_docset_to_docarray($qdoc);
	
	my ($schema, $table) = split(/\./, $coll);
	@$opinfo{'opname','schema','table', 'bson'} = ('OP_INSERT', $schema, $table, \@dec_docset );
	}
elsif($opcode_d == 2004) # OP_QUERY
	{
	my (undef, $coll) = unpack("lZ*", $request); # Flags, collection, skip, return, the rest
	my $qdoc = substr($request, 13+length($coll)); # 3L + strlen + null-termination

	my ($schema, $table) = split(/\./, $coll);
	@$opinfo{'opname','schema','table', 'bson'} = ('OP_QUERY', $schema, $table, BSON::decode($qdoc, ixhash=>1) );
	}
elsif($opcode_d == 2005) # OP_GET_MORE
	{
	my (undef, $coll) = unpack("lZ*", $request);
	my ($schema, $table) = split(/\./, $coll);
	@$opinfo{'opname','schema','table'} = ('OP_GET_MORE', $schema, $table);
	}
elsif($opcode_d == 2006) # OP_DELETE
	{
	my (undef, $coll) = unpack("lZ*", $request);
	my $qdoc = substr($request, 9+length($coll)); # 2L + strlen + null-termination
	my ($schema, $table) = split(/\./, $coll);
	@$opinfo{'opname','schema','table', 'bson'} = ('OP_DELETE', $schema, $table, BSON::decode($qdoc, ixhash=>1) );
	}
elsif($opcode_d == 2007) # OP_KILL_CURSORS
	{
	@$opinfo{'opname','schema','table'} = ('OP_KILL_CURSORS', undef, undef);
	}
elsif($opcode_d == 1) # OP_REPLY
	{
	my(undef, $cursorid, $startfrom, $numret) = unpack("lqll", $request); # first field is response flags
	my $qdoc = substr($request, 20); # 5L
	my @dec_docset = map
				{
				BSON::decode($_, ixhash=>1)
				} bson_docset_to_docarray($qdoc, $numret);
	@$opinfo{'opname', 'schema', 'table', 'bson'} = ('OP_REPLY', undef, undef, 
								\@dec_docset
								);
	#@$opinfo{'opname', 'schema', 'table'} = ('OP_REPLY', undef, undef); # First try with no BSON decode
	}
else
	{
	@$opinfo{'opname','schema','table'} = ('OP_UNKNOWN', undef, undef);
	}
}

##################
# Poor man's connection pool

sub ensure_mongo_connection
{	# Make sure there's a connection to this server.
	# Return that connection.
my ($pool, $host, $port) = @_;

if(! defined($$pool{"$host$port"})) # TODO OR if the connection is no longer up....
	{
	my $conn = MongoDB::_Link->new("$host:$port");
	$conn->connect();
	$$pool{"$host$port"} = $conn;
	}
return $$pool{"$host$port"};
}


##################
sub main
{	# When you use Net::Server, your main function is primarily
	# to prepare you to enter the event loop the module provides
$proxy = setup_proxy($proxycfg);
MongoProxy->run(port => $proxy_lport);
}

